<?php
declare(strict_types=1);
define('SYNC_ROOT', __DIR__);
require_once SYNC_ROOT . '/lib/config.php';

$pageTitle = 'Terms of Service — Syncsity';
$pageDesc  = 'The terms governing the use of Syncsity\'s site and free Revenue Intelligence Report.';

include SYNC_ROOT . '/partials/head.php';
include SYNC_ROOT . '/partials/header.php';
?>

<section class="section section--hero">
  <div class="container container--md">
    <span class="eyebrow">Terms of Service</span>
    <h1 style="margin: var(--s-4) 0 var(--s-6);">Plain-English terms.</h1>
    <p class="lead">Last updated: <?= date('j F Y') ?>. By using syncsity.com you agree to these terms.</p>
  </div>
</section>

<section class="section section--tight">
  <div class="container container--md" style="font-size:1.02rem; line-height:1.75; color: var(--text-muted);">
    <h2 style="color: var(--text);">1. Who we are</h2>
    <p>Syncsity Ltd ("Syncsity", "we", "us") is a UK-incorporated company. Our website is <a href="https://syncsity.com">syncsity.com</a>. Our contact email is <a href="mailto:edward@syncsity.com">edward@syncsity.com</a>.</p>

    <h2 style="color: var(--text); margin-top: var(--s-10);">2. The free Revenue Intelligence Report</h2>
    <p>The Revenue Intelligence Report is provided <strong style="color:var(--text);">as-is and for informational purposes only</strong>. It is generated by an AI system based on the answers you provide and publicly available information about your business and industry. It is not financial, legal, or strategic advice and does not create a contractual or fiduciary relationship.</p>
    <p>You are responsible for any decisions you make based on the report. Where the report makes specific claims (revenue leakage estimates, market sizing, etc.), these are educated approximations. They should be tested against your real numbers before any action is taken.</p>

    <h2 style="color: var(--text); margin-top: var(--s-10);">3. Acceptable use</h2>
    <ul style="display:grid; gap: var(--s-2); padding-left: var(--s-6); list-style: disc;">
      <li>You will not submit assessments using a false identity or email you don't control.</li>
      <li>You will not abuse the service (rapid-fire submissions, scraping, automated probing).</li>
      <li>You will not resell, white-label, or redistribute the report without our written permission.</li>
      <li>You will not attempt to reverse-engineer the assessment or the prompt logic.</li>
    </ul>

    <h2 style="color: var(--text); margin-top: var(--s-10);">4. Intellectual property</h2>
    <p>The site, the assessment, the prompt logic, and the report templates are the intellectual property of Syncsity Ltd. The content of <em>your</em> report — based on your answers and your business — is yours to use freely within your own organisation.</p>

    <h2 style="color: var(--text); margin-top: var(--s-10);">5. Engagements</h2>
    <p>If you engage Syncsity for paid work (Strategy Session or Engagement), separate written terms will apply, signed by both parties before any work begins. The terms on this page do not govern paid engagements.</p>

    <h2 style="color: var(--text); margin-top: var(--s-10);">6. Limitation of liability</h2>
    <p>To the maximum extent permitted by law, Syncsity is not liable for any indirect, incidental, special, or consequential losses arising from your use of the free assessment or report. Our total liability for the free service is limited to nil — it is, after all, free.</p>
    <p>Nothing in these terms excludes liability for death, personal injury caused by negligence, or any liability that cannot be excluded under English law.</p>

    <h2 style="color: var(--text); margin-top: var(--s-10);">7. Privacy</h2>
    <p>Our handling of personal data is described in the <a href="/privacy">Privacy Policy</a>, which forms part of these terms.</p>

    <h2 style="color: var(--text); margin-top: var(--s-10);">8. Governing law</h2>
    <p>These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England.</p>

    <h2 style="color: var(--text); margin-top: var(--s-10);">9. Changes</h2>
    <p>We may update these terms from time to time. Material changes will be flagged on the home page for at least 14 days before they take effect.</p>
  </div>
</section>

<?php include SYNC_ROOT . '/partials/footer.php'; ?>
