<?php
/**
 * Terms of Service — migrated from terms.html to use the universal partials.
 *
 * Page lives at site root, so $page_path_prefix = '/'.
 */

$page_path_prefix = '/';
$page_title       = 'Terms of Service | Syncsity';
$page_description = 'The terms governing the use of Syncsity\'s site and free Revenue Intelligence Report. Plain-English ToS, England & Wales jurisdiction.';
$page_canonical   = 'https://syncsity.com/terms.php';
$page_modified    = '2026-05-01T00:00:00Z';
$page_breadcrumb  = [
    ['Home', 'https://syncsity.com/'],
    ['Terms of Service', 'https://syncsity.com/terms.php'],
];

// Page-specific JSON-LD: explicit Article-style metadata for the legal doc.
// Helps LLM crawlers cite the policy version + date when summarising.
$page_extra_jsonld = <<<'JSONLD'

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "WebPage",
  "@id": "https://syncsity.com/terms.php#legal",
  "name": "Syncsity Terms of Service",
  "description": "Plain-English terms governing use of Syncsity's free Revenue Intelligence Report.",
  "lastReviewed": "2026-05-01",
  "reviewedBy": { "@id": "https://syncsity.com/#organization" },
  "mainContentOfPage": {
    "@type": "WebPageElement",
    "cssSelector": "article.prose"
  },
  "specialty": "Legal Terms of Service",
  "inLanguage": "en-GB"
}
</script>
JSONLD;

include __DIR__ . '/partials/site-head.php';
?>

<style>
/* Page-specific: prose article styling for the legal text. Universal nav/footer
   are loaded from site-nav.css. */
.legal-hero {
  padding: 56px 0 32px;
  border-bottom: 1px solid var(--border);
}
.legal-hero .eyebrow {
  display: inline-block; padding: 4px 12px;
  background: rgba(252,163,17,0.14); color: var(--orange);
  border-radius: 9999px; font-size: 12px; font-weight: 600;
  letter-spacing: 0.06em; text-transform: uppercase;
}
.legal-hero h1 {
  margin: 16px 0 12px; font-size: clamp(34px, 4.4vw, 48px);
  font-weight: 700; color: #fff; letter-spacing: -0.02em;
}
.legal-hero .lead {
  color: var(--text-muted); font-size: 16px; max-width: 640px;
}
.legal-body { padding: 48px 0 80px; }
.prose { color: var(--text-muted); font-size: 15.5px; line-height: 1.7; }
.prose h2 {
  color: #fff; font-size: 22px; font-weight: 700;
  margin: 36px 0 12px; letter-spacing: -0.01em;
}
.prose h2:first-child { margin-top: 0; }
.prose p { margin: 0 0 14px; }
.prose ul { margin: 0 0 16px; padding-left: 22px; }
.prose li { margin-bottom: 8px; }
.prose a { color: var(--blue-400); text-decoration: underline; text-underline-offset: 3px; }
.prose a:hover { color: #fff; }
.prose strong { color: #fff; }
.prose em { color: rgba(255,255,255,0.85); }
</style>
</head>
<body>

<?php include __DIR__ . '/partials/site-nav.php'; ?>

<main id="main" aria-label="Terms of Service">

  <section class="legal-hero">
    <div class="container container--md">
      <span class="eyebrow">Legal</span>
      <h1>Terms of Service</h1>
      <p class="lead">Plain-English. Last updated 1 May 2026. England &amp; Wales jurisdiction.</p>
    </div>
  </section>

  <section class="legal-body">
    <div class="container container--md">
      <article class="prose">
        <h2>1. Who we are</h2>
        <p>Syncsity Ltd ("Syncsity", "we", "us") is a UK-incorporated company. Our website is <a href="/">syncsity.com</a>. Our contact email is <a href="mailto:edward@syncsity.com">edward@syncsity.com</a>.</p>

        <h2>2. The free Revenue Intelligence Report</h2>
        <p>The Revenue Intelligence Report is provided <strong>as-is and for informational purposes only</strong>. It is generated by an AI system based on the answers you provide and publicly available information about your business and industry. It is not financial, legal, or strategic advice and does not create a contractual or fiduciary relationship.</p>
        <p>You are responsible for any decisions you make based on the report. Where the report makes specific claims (revenue leakage estimates, market sizing, etc.), these are educated approximations. They should be tested against your real numbers before any action is taken.</p>

        <h2>3. Acceptable use</h2>
        <ul>
          <li>You will not submit assessments using a false identity or email you don't control.</li>
          <li>You will not abuse the service (rapid-fire submissions, scraping, automated probing).</li>
          <li>You will not resell, white-label, or redistribute the report without our written permission.</li>
          <li>You will not attempt to reverse-engineer the assessment or the prompt logic.</li>
        </ul>

        <h2>4. Intellectual property</h2>
        <p>The site, the assessment, the prompt logic, and the report templates are the intellectual property of Syncsity Ltd. The content of <em>your</em> report &mdash; based on your answers and your business &mdash; is yours to use freely within your own organisation.</p>

        <h2>5. Engagements</h2>
        <p>If you engage Syncsity for paid work (Strategy Session or Engagement), separate written terms will apply, signed by both parties before any work begins. The terms on this page do not govern paid engagements.</p>

        <h2>6. Limitation of liability</h2>
        <p>To the maximum extent permitted by law, Syncsity is not liable for any indirect, incidental, special, or consequential losses arising from your use of the free assessment or report. Our total liability for the free service is limited to nil &mdash; it is, after all, free.</p>
        <p>Nothing in these terms excludes liability for death, personal injury caused by negligence, or any liability that cannot be excluded under English law.</p>

        <h2>7. Privacy</h2>
        <p>Our handling of personal data is described in the <a href="/privacy.html">Privacy Policy</a>, which forms part of these terms.</p>

        <h2>8. Governing law</h2>
        <p>These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England.</p>

        <h2>9. Changes</h2>
        <p>We may update these terms from time to time. Material changes will be flagged on the home page for at least 14 days before they take effect.</p>
      </article>
    </div>
  </section>

</main>

<?php include __DIR__ . '/partials/site-footer.php'; ?>
